In [1]:
import pandas as pd
import numpy as np

In [2]:
movie = pd.read_csv('/content/movie_classification.csv')
movie.head(10)

,Marketing expense,Production expense,Multiplex coverage,Budget,Movie_length,Lead_ Actor_Rating,Lead_Actress_rating,Director_rating,Producer_rating,Critic_rating,Trailer_views,3D_available,Time_taken,Twitter_hastags,Genre,Avg_age_actors,Num_multiplex,Collection,Start_Tech_Oscar
0,20.1264,59.62,0.462,36524.125,138.7,7.825,8.095,7.910,7.995,7.94,527367,YES,109.60,223.840,Thriller,23,494,48000,1
1,20.5462,69.14,0.531,35668.655,152.4,7.505,7.650,7.440,7.470,7.44,494055,NO,146.64,243.456,Drama,42,462,43200,0
2,20.5458,69.14,0.531,39912.675,134.6,7.485,7.570,7.495,7.515,7.44,547051,NO,147.88,2022.400,Comedy,38,458,69400,1
3,20.6474,59.36,0.542,38873.890,119.3,6.895,7.035,6.920,7.020,8.26,516279,YES,185.36,225.344,Drama,45,472,66800,1
4,21.3810,59.36,0.542,39701.585,127.7,6.920,7.070,6.815,7.070,8.26,531448,NO,176.48,225.792,Drama,55,395,72400,1
5,20.5970,59.36,0.542,35718.650,132.2,6.890,7.100,6.885,7.005,7.26,498425,YES,143.48,284.592,Comedy,53,460,57400,0
6,21.7658,70.74,0.476,33396.660,140.1,7.065,7.265,7.150,7.400,8.96,459241,YES,139.16,243.664,Thriller,41,522,45800,0
7,22.8910,70.74,0.476,34285.460,169.6,6.980,7.075,6.875,7.170,7.96,400821,NO,116.84,243.536,Drama,56,571,44200,0
8,24.2248,70.74,0.476,31280.205,173.5,6.910,7.075,6.850,7.000,7.96,295168,YES,118.60,242.640,Comedy,55,564,33000,1
9,23.4008,70.74,0.476,33352.220,159.4,6.665,6.725,6.575,6.855,7.96,412012,YES,189.56,283.024,Thriller,45,508,37800,1

In [3]:
movie.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Marketing expense    506 non-null    float64
 1   Production expense   506 non-null    float64
 2   Multiplex coverage   506 non-null    float64
 3   Budget               506 non-null    float64
 4   Movie_length         506 non-null    float64
 5   Lead_ Actor_Rating   506 non-null    float64
 6   Lead_Actress_rating  506 non-null    float64
 7   Director_rating      506 non-null    float64
 8   Producer_rating      506 non-null    float64
 9   Critic_rating        506 non-null    float64
 10  Trailer_views        506 non-null    int64
 11  3D_available         506 non-null    object
 12  Time_taken           494 non-null    float64
 13  Twitter_hastags      506 non-null    float64
 14  Genre                506 non-null    object
 15  Avg_age_actors       506 non-null    int64
 16  Num_multiplex        506 non-null    int64
 17  Collection           506 non-null    int64
 18  Start_Tech_Oscar     506 non-null    int64
dtypes: float64(12), int64(5), object(2)
memory usage: 75.2+ KB

In [4]:
movie.duplicated().sum()

0

In [5]:
movie.isnull().sum()

Marketing expense       0
Production expense      0
Multiplex coverage      0
Budget                  0
Movie_length            0
Lead_ Actor_Rating      0
Lead_Actress_rating     0
Director_rating         0
Producer_rating         0
Critic_rating           0
Trailer_views           0
3D_available            0
Time_taken             12
Twitter_hastags         0
Genre                   0
Avg_age_actors          0
Num_multiplex           0
Collection              0
Start_Tech_Oscar        0
dtype: int64

In [6]:
movie.isnull().sum()/len(movie)*100

Marketing expense      0.000000
Production expense     0.000000
Multiplex coverage     0.000000
Budget                 0.000000
Movie_length           0.000000
Lead_ Actor_Rating     0.000000
Lead_Actress_rating    0.000000
Director_rating        0.000000
Producer_rating        0.000000
Critic_rating          0.000000
Trailer_views          0.000000
3D_available           0.000000
Time_taken             2.371542
Twitter_hastags        0.000000
Genre                  0.000000
Avg_age_actors         0.000000
Num_multiplex          0.000000
Collection             0.000000
Start_Tech_Oscar       0.000000
dtype: float64

In [8]:
movie.mean = movie.copy(deep=True) # jika imputasi dengan mean
movie.modus = movie.copy(deep=True) # jika imputasi dengan modus
movie.median = movie.copy(deep=True) # jika imputasi dengan median

<ipython-input-8-122f0b8fa32c>:2: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  movie.modus = movie.copy(deep=True) # jika imputasi dengan modus

In [11]:
# Mengisi missing value di kolom Time_taken dengan mean
movie.mean.fillna({'Time_taken': movie.mean['Time_taken'].mean()}, inplace=True)
# Mengisi missing value di kolom Time_taken dengan modus
movie.modus.fillna({'Time_taken': movie.modus['Time_taken'].mode()[0]}, inplace=True)
# Mengisi missing value di kolom Time_taken dengan median
movie.median.fillna({'Time_taken': movie.median['Time_taken'].median()}, inplace=True)

In [13]:
movie.mean.isnull().sum()

Marketing expense      0
Production expense     0
Multiplex coverage     0
Budget                 0
Movie_length           0
Lead_ Actor_Rating     0
Lead_Actress_rating    0
Director_rating        0
Producer_rating        0
Critic_rating          0
Trailer_views          0
3D_available           0
Time_taken             0
Twitter_hastags        0
Genre                  0
Avg_age_actors         0
Num_multiplex          0
Collection             0
Start_Tech_Oscar       0
dtype: int64

In [15]:
movie.modus.isnull().sum()

Marketing expense      0
Production expense     0
Multiplex coverage     0
Budget                 0
Movie_length           0
Lead_ Actor_Rating     0
Lead_Actress_rating    0
Director_rating        0
Producer_rating        0
Critic_rating          0
Trailer_views          0
3D_available           0
Time_taken             0
Twitter_hastags        0
Genre                  0
Avg_age_actors         0
Num_multiplex          0
Collection             0
Start_Tech_Oscar       0
dtype: int64

In [16]:
movie.median.isnull().sum()

Marketing expense      0
Production expense     0
Multiplex coverage     0
Budget                 0
Movie_length           0
Lead_ Actor_Rating     0
Lead_Actress_rating    0
Director_rating        0
Producer_rating        0
Critic_rating          0
Trailer_views          0
3D_available           0
Time_taken             0
Twitter_hastags        0
Genre                  0
Avg_age_actors         0
Num_multiplex          0
Collection             0
Start_Tech_Oscar       0
dtype: int64

In [18]:
# Simpan data ke csv
movie.mean.to_csv('/content/movie_classification.csv', index=False)
movie.modus.to_csv('/content/movie_classification.csv', index=False)
movie.median.to_csv('/content/movie_classification.csv', index=False)

In [20]:
# Simpan data ke exel
movie.mean.to_excel('/content/movie_classification.xlsx', index=False)
movie.modus.to_excel('/content/movie_classification.xlsx', index=False)
movie.median.to_excel('/content/movie_classification.xlsx', index=False)